
        tailwind.config = {
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface-variant": "#e2e3e0",
                        "inverse-primary": "#93d5af",
                        "tertiary-fixed": "#ffdad8",
                        "surface-container-low": "#f4f4f1",
                        "on-tertiary-container": "#ff908f",
                        "outline-variant": "#bfc9c1",
                        "primary-fixed-dim": "#93d5af",
                        "secondary-fixed-dim": "#bfc9c6",
                        "inverse-on-surface": "#f1f1ef",
                        "primary-fixed": "#aef1ca",
                        "on-primary": "#ffffff",
                        "primary": "#003420",
                        "on-secondary": "#ffffff",
                        "background": "#f9f9f7",
                        "on-secondary-fixed-variant": "#3f4947",
                        "tertiary-fixed-dim": "#ffb3b1",
                        "on-primary-container": "#7cbd99",
                        "on-error": "#ffffff",
                        "outline": "#707972",
                        "on-surface-variant": "#404943",
                        "surface-container-lowest": "#ffffff",
                        "on-primary-fixed-variant": "#075135",
                        "secondary-fixed": "#dbe5e2",
                        "error": "#ba1a1a",
                        "surface-tint": "#296a4b",
                        "surface-dim": "#dadad8",
                        "on-tertiary": "#ffffff",
                        "on-surface": "#1a1c1b",
                        "error-container": "#ffdad6",
                        "on-background": "#1a1c1b",
                        "inverse-surface": "#2f3130",
                        "tertiary-container": "#8b001a",
                        "surface-container-highest": "#e2e3e0",
                        "secondary-container": "#dbe5e2",
                        "on-secondary-fixed": "#141d1c",
                        "secondary": "#57605e",
                        "surface": "#f9f9f7",
                        "on-tertiary-fixed": "#410007",
                        "on-error-container": "#93000a",
                        "on-secondary-container": "#5d6664",
                        "on-tertiary-fixed-variant": "#92001c",
                        "surface-bright": "#f9f9f7",
                        "surface-container": "#eeeeec",
                        "on-primary-fixed": "#002112",
                        "tertiary": "#61000f",
                        "primary-container": "#004d31",
                        "surface-container-high": "#e8e8e6"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "spacing": {
                        "margin-desktop": "32px",
                        "gutter": "24px",
                        "base": "8px",
                        "margin-mobile": "16px",
                        "container-max": "1280px"
                    },
                    "fontFamily": {
                        "body-sm": ["Hanken Grotesk"],
                        "body-lg": ["Hanken Grotesk"],
                        "title-md": ["Hanken Grotesk"],
                        "label-md": ["Hanken Grotesk"],
                        "headline-lg": ["Hanken Grotesk"],
                        "headline-xl": ["Hanken Grotesk"],
                        "label-sm": ["Hanken Grotesk"],
                        "headline-lg-mobile": ["Hanken Grotesk"]
                    },
                    "fontSize": {
                        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
                        "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
                        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
                    }
                },
            },
        }
