
      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "on-background": "#1a1c1b",
                    "secondary": "#57605e",
                    "on-error": "#ffffff",
                    "on-tertiary-fixed-variant": "#92001c",
                    "on-tertiary-container": "#ff908f",
                    "surface-container-high": "#e8e8e6",
                    "primary": "#003420",
                    "surface-container-low": "#f4f4f1",
                    "on-primary-fixed": "#002112",
                    "tertiary": "#61000f",
                    "outline": "#707972",
                    "secondary-container": "#dbe5e2",
                    "surface-variant": "#e2e3e0",
                    "on-tertiary-fixed": "#410007",
                    "on-secondary-fixed": "#141d1c",
                    "surface-container-lowest": "#ffffff",
                    "surface-dim": "#dadad8",
                    "on-surface": "#1a1c1b",
                    "inverse-on-surface": "#f1f1ef",
                    "secondary-fixed": "#dbe5e2",
                    "on-primary-fixed-variant": "#075135",
                    "inverse-primary": "#93d5af",
                    "error": "#ba1a1a",
                    "primary-fixed": "#aef1ca",
                    "on-secondary": "#ffffff",
                    "on-error-container": "#93000a",
                    "on-primary-container": "#7cbd99",
                    "surface-bright": "#f9f9f7",
                    "surface": "#f9f9f7",
                    "surface-container": "#eeeeec",
                    "inverse-surface": "#2f3130",
                    "secondary-fixed-dim": "#bfc9c6",
                    "on-secondary-container": "#5d6664",
                    "tertiary-container": "#8b001a",
                    "on-primary": "#ffffff",
                    "tertiary-fixed-dim": "#ffb3b1",
                    "tertiary-fixed": "#ffdad8",
                    "primary-container": "#004d31",
                    "on-secondary-fixed-variant": "#3f4947",
                    "primary-fixed-dim": "#93d5af",
                    "on-tertiary": "#ffffff",
                    "surface-container-highest": "#e2e3e0",
                    "background": "#f9f9f7",
                    "surface-tint": "#296a4b",
                    "on-surface-variant": "#404943",
                    "outline-variant": "#bfc9c1",
                    "error-container": "#ffdad6"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "margin-mobile": "16px",
                    "gutter": "24px",
                    "container-max": "1280px",
                    "margin-desktop": "32px",
                    "base": "8px"
            },
            "fontFamily": {
                    "headline-xl": ["Hanken Grotesk"],
                    "body-lg": ["Hanken Grotesk"],
                    "headline-lg": ["Hanken Grotesk"],
                    "label-md": ["Hanken Grotesk"],
                    "label-sm": ["Hanken Grotesk"],
                    "headline-lg-mobile": ["Hanken Grotesk"],
                    "body-sm": ["Hanken Grotesk"],
                    "title-md": ["Hanken Grotesk"]
            },
            "fontSize": {
                    "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                    "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                    "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                    "label-md": ["14px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600"}],
                    "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                    "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                    "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                    "title-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
            }
          },
        },
      }
